-- ============================================================
-- S&P 100 Şirketleri (company_analysis_core)
-- ============================================================
INSERT INTO company_analysis_core (symbol, name, sector) VALUES
('AAPL', 'Apple Inc.', 'Technology'),
('ABBV', 'AbbVie Inc.', 'Healthcare'),
('ABT', 'Abbott Laboratories', 'Healthcare'),
('ACN', 'Accenture plc', 'Technology'),
('ADBE', 'Adobe Inc.', 'Technology'),
('AIG', 'American International Group', 'Financial Services'),
('AMGN', 'Amgen Inc.', 'Healthcare'),
('AMT', 'American Tower Corporation', 'Real Estate'),
('AMZN', 'Amazon.com Inc.', 'Consumer Cyclical'),
('AVGO', 'Broadcom Inc.', 'Technology'),
('AXP', 'American Express Company', 'Financial Services'),
('BA', 'The Boeing Company', 'Industrials'),
('BAC', 'Bank of America Corporation', 'Financial Services'),
('BK', 'The Bank of New York Mellon', 'Financial Services'),
('BKNG', 'Booking Holdings Inc.', 'Consumer Cyclical'),
('BLK', 'BlackRock Inc.', 'Financial Services'),
('BMY', 'Bristol-Myers Squibb Company', 'Healthcare'),
('BRK.B', 'Berkshire Hathaway Inc.', 'Financial Services'),
('C', 'Citigroup Inc.', 'Financial Services'),
('CAT', 'Caterpillar Inc.', 'Industrials'),
('CHTR', 'Charter Communications Inc.', 'Communication Services'),
('CL', 'Colgate-Palmolive Company', 'Consumer Defensive'),
('CMCSA', 'Comcast Corporation', 'Communication Services'),
('COF', 'Capital One Financial', 'Financial Services'),
('COP', 'ConocoPhillips', 'Energy'),
('COST', 'Costco Wholesale Corporation', 'Consumer Defensive'),
('CRM', 'Salesforce Inc.', 'Technology'),
('CSCO', 'Cisco Systems Inc.', 'Technology'),
('CVS', 'CVS Health Corporation', 'Healthcare'),
('CVX', 'Chevron Corporation', 'Energy'),
('DE', 'Deere & Company', 'Industrials'),
('DHR', 'Danaher Corporation', 'Healthcare'),
('DIS', 'The Walt Disney Company', 'Communication Services'),
('DOW', 'Dow Inc.', 'Basic Materials'),
('DUK', 'Duke Energy Corporation', 'Utilities'),
('EMR', 'Emerson Electric Co.', 'Industrials'),
('EXC', 'Exelon Corporation', 'Utilities'),
('F', 'Ford Motor Company', 'Consumer Cyclical'),
('FDX', 'FedEx Corporation', 'Industrials'),
('GD', 'General Dynamics Corporation', 'Industrials'),
('GE', 'GE Aerospace', 'Industrials'),
('GILD', 'Gilead Sciences Inc.', 'Healthcare'),
('GM', 'General Motors Company', 'Consumer Cyclical'),
('GOOG', 'Alphabet Inc. (Class C)', 'Communication Services'),
('GOOGL', 'Alphabet Inc. (Class A)', 'Communication Services'),
('GS', 'The Goldman Sachs Group', 'Financial Services'),
('HD', 'The Home Depot Inc.', 'Consumer Cyclical'),
('HON', 'Honeywell International', 'Industrials'),
('IBM', 'International Business Machines', 'Technology'),
('INTC', 'Intel Corporation', 'Technology'),
('INTU', 'Intuit Inc.', 'Technology'),
('ISRG', 'Intuitive Surgical Inc.', 'Healthcare'),
('JNJ', 'Johnson & Johnson', 'Healthcare'),
('JPM', 'JPMorgan Chase & Co.', 'Financial Services'),
('KHC', 'The Kraft Heinz Company', 'Consumer Defensive'),
('KO', 'The Coca-Cola Company', 'Consumer Defensive'),
('LIN', 'Linde plc', 'Basic Materials'),
('LLY', 'Eli Lilly and Company', 'Healthcare'),
('LMT', 'Lockheed Martin Corporation', 'Industrials'),
('LOW', 'Lowes Companies Inc.', 'Consumer Cyclical'),
('MA', 'Mastercard Incorporated', 'Financial Services'),
('MCD', 'McDonalds Corporation', 'Consumer Cyclical'),
('MDLZ', 'Mondelez International', 'Consumer Defensive'),
('MDT', 'Medtronic plc', 'Healthcare'),
('MET', 'MetLife Inc.', 'Financial Services'),
('META', 'Meta Platforms Inc.', 'Communication Services'),
('MMM', '3M Company', 'Industrials'),
('MO', 'Altria Group Inc.', 'Consumer Defensive'),
('MRK', 'Merck & Co. Inc.', 'Healthcare'),
('MS', 'Morgan Stanley', 'Financial Services'),
('MSFT', 'Microsoft Corporation', 'Technology'),
('NEE', 'NextEra Energy Inc.', 'Utilities'),
('NFLX', 'Netflix Inc.', 'Communication Services'),
('NKE', 'NIKE Inc.', 'Consumer Cyclical'),
('NVDA', 'NVIDIA Corporation', 'Technology'),
('ORCL', 'Oracle Corporation', 'Technology'),
('PEP', 'PepsiCo Inc.', 'Consumer Defensive'),
('PFE', 'Pfizer Inc.', 'Healthcare'),
('PG', 'The Procter & Gamble Company', 'Consumer Defensive'),
('PM', 'Philip Morris International', 'Consumer Defensive'),
('PYPL', 'PayPal Holdings Inc.', 'Financial Services'),
('QCOM', 'QUALCOMM Incorporated', 'Technology'),
('RTX', 'RTX Corporation', 'Industrials'),
('SBUX', 'Starbucks Corporation', 'Consumer Cyclical'),
('SCHW', 'The Charles Schwab Corporation', 'Financial Services'),
('SO', 'The Southern Company', 'Utilities'),
('SPG', 'Simon Property Group', 'Real Estate'),
('T', 'AT&T Inc.', 'Communication Services'),
('TGT', 'Target Corporation', 'Consumer Cyclical'),
('TMO', 'Thermo Fisher Scientific', 'Healthcare'),
('TMUS', 'T-Mobile US Inc.', 'Communication Services'),
('TSLA', 'Tesla Inc.', 'Consumer Cyclical'),
('TXN', 'Texas Instruments Incorporated', 'Technology'),
('UNH', 'UnitedHealth Group Incorporated', 'Healthcare'),
('UNP', 'Union Pacific Corporation', 'Industrials'),
('UPS', 'United Parcel Service Inc.', 'Industrials'),
('USB', 'U.S. Bancorp', 'Financial Services'),
('V', 'Visa Inc.', 'Financial Services'),
('VZ', 'Verizon Communications Inc.', 'Communication Services'),
('WBA', 'Walgreens Boots Alliance', 'Healthcare'),
('WFC', 'Wells Fargo & Company', 'Financial Services'),
('WMT', 'Walmart Inc.', 'Consumer Defensive'),
('XOM', 'Exxon Mobil Corporation', 'Energy');

-- ============================================================
-- BIST 100 Şirketleri (company_analysis_tr_core)
-- ============================================================
INSERT INTO company_analysis_tr_core (symbol, name, sector) VALUES
('AEFES.IS', 'Anadolu Efes Biracılık', 'Gıda & İçecek'),
('AFYON.IS', 'Afyon Çimento', 'Çimento'),
('AGESA.IS', 'AgeSA Hayat ve Emeklilik', 'Sigorta'),
('AKBNK.IS', 'Akbank T.A.Ş.', 'Bankacılık'),
('AKCNS.IS', 'Akçansa Çimento', 'Çimento'),
('AKFGY.IS', 'Akfen GYO', 'Gayrimenkul'),
('AKSA.IS', 'Aksa Akrilik Kimya', 'Kimya'),
('AKSEN.IS', 'Aksa Enerji Üretim', 'Enerji'),
('ALARK.IS', 'Alarko Holding', 'Holding'),
('ALFAS.IS', 'Alfa Solar Enerji', 'Enerji'),
('ALKIM.IS', 'Alkim Alkali Kimya', 'Kimya'),
('ARCLK.IS', 'Arçelik A.Ş.', 'Dayanıklı Tüketim'),
('ARDYZ.IS', 'Anadolu Grubu Holding', 'Holding'),
('ASELS.IS', 'ASELSAN Elektronik', 'Savunma & Havacılık'),
('AYDEM.IS', 'Aydem Yenilenebilir Enerji', 'Enerji'),
('BAGFS.IS', 'Bagfaş Bandırma Gübre', 'Kimya'),
('BASGZ.IS', 'Başkent Doğalgaz', 'Enerji'),
('BERA.IS', 'Bera Holding', 'Holding'),
('BIMAS.IS', 'BİM Birleşik Mağazalar', 'Perakende'),
('BIOEN.IS', 'Biotrend Çevre ve Enerji', 'Enerji'),
('BRISA.IS', 'Brisa Bridgestone Sabancı', 'Otomotiv'),
('BRYAT.IS', 'Borusan Yatırım', 'Holding'),
('BUCIM.IS', 'Bursa Çimento', 'Çimento'),
('CCOLA.IS', 'Coca-Cola İçecek', 'Gıda & İçecek'),
('CEMTS.IS', 'Çemtaş Çelik Makina', 'Metal & Çelik'),
('CIMSA.IS', 'Çimsa Çimento', 'Çimento'),
('DEVA.IS', 'Deva Holding', 'İlaç'),
('DOAS.IS', 'Doğuş Otomotiv', 'Otomotiv'),
('DOHOL.IS', 'Doğan Holding', 'Holding'),
('ECILC.IS', 'Eczacıbaşı İlaç', 'İlaç'),
('EGEEN.IS', 'Ege Endüstri', 'Otomotiv'),
('EKGYO.IS', 'Emlak Konut GYO', 'Gayrimenkul'),
('ENJSA.IS', 'Enerjisa Enerji', 'Enerji'),
('ENKAI.IS', 'Enka İnşaat', 'İnşaat'),
('EREGL.IS', 'Ereğli Demir ve Çelik', 'Metal & Çelik'),
('EUPWR.IS', 'Europower Enerji', 'Enerji'),
('FROTO.IS', 'Ford Otosan', 'Otomotiv'),
('GARAN.IS', 'Garanti BBVA Bankası', 'Bankacılık'),
('GENIL.IS', 'Gen İlaç ve Sağlık', 'İlaç'),
('GESAN.IS', 'Giresun Sanayi', 'Sanayi'),
('GLYHO.IS', 'Global Yatırım Holding', 'Holding'),
('GUBRF.IS', 'Gübre Fabrikaları', 'Kimya'),
('HALKB.IS', 'Türkiye Halk Bankası', 'Bankacılık'),
('HEKTS.IS', 'Hektaş Ticaret', 'Kimya'),
('ISCTR.IS', 'Türkiye İş Bankası', 'Bankacılık'),
('ISGYO.IS', 'İş GYO', 'Gayrimenkul'),
('KAYSE.IS', 'Kayseri Şeker Fabrikası', 'Gıda & İçecek'),
('KCAER.IS', 'Kocaer Çelik', 'Metal & Çelik'),
('KCHOL.IS', 'Koç Holding', 'Holding'),
('KLSER.IS', 'Kaleseramik', 'Seramik'),
('KMPUR.IS', 'Kömürcüoğlu', 'Sanayi'),
('KONTR.IS', 'Kontrolmatik Teknoloji', 'Teknoloji'),
('KOZAA.IS', 'Koza Anadolu Metal Madencilik', 'Madencilik'),
('KOZAL.IS', 'Koza Altın İşletmeleri', 'Madencilik'),
('KRDMD.IS', 'Kardemir (D)', 'Metal & Çelik'),
('KZBGY.IS', 'Kızılbük GYO', 'Gayrimenkul'),
('LOGO.IS', 'Logo Yazılım', 'Teknoloji'),
('MGROS.IS', 'Migros Ticaret', 'Perakende'),
('MPARK.IS', 'MLP Sağlık Hizmetleri', 'Sağlık'),
('OBAMS.IS', 'Oba Makarnacılık', 'Gıda & İçecek'),
('ODAS.IS', 'Odaş Elektrik', 'Enerji'),
('OTKAR.IS', 'Otokar Otomotiv ve Savunma', 'Otomotiv'),
('OYAKC.IS', 'Oyak Çimento', 'Çimento'),
('PENTA.IS', 'Penta Teknoloji', 'Teknoloji'),
('PETKM.IS', 'Petkim Petrokimya', 'Kimya'),
('PGSUS.IS', 'Pegasus Hava Taşımacılığı', 'Ulaşım'),
('QUAGR.IS', 'QUA Granite', 'Seramik'),
('SAHOL.IS', 'Sabancı Holding', 'Holding'),
('SASA.IS', 'SASA Polyester Sanayi', 'Kimya'),
('SELEC.IS', 'Selçuk Ecza Deposu', 'İlaç'),
('SISE.IS', 'Şişecam', 'Cam & Seramik'),
('SKBNK.IS', 'Şekerbank', 'Bankacılık'),
('SOKM.IS', 'Şok Marketler', 'Perakende'),
('TAVHL.IS', 'TAV Havalimanları', 'Ulaşım'),
('TCELL.IS', 'Turkcell İletişim', 'Telekomünikasyon'),
('THYAO.IS', 'Türk Hava Yolları', 'Ulaşım'),
('TKFEN.IS', 'Tekfen Holding', 'Holding'),
('TKNSA.IS', 'Teknosa İç ve Dış Ticaret', 'Perakende'),
('TMSN.IS', 'Tümosan Motor', 'Otomotiv'),
('TOASO.IS', 'Tofaş Türk Otomobil', 'Otomotiv'),
('TTKOM.IS', 'Türk Telekomünikasyon', 'Telekomünikasyon'),
('TRGYO.IS', 'Torunlar GYO', 'Gayrimenkul'),
('TTRAK.IS', 'Türk Traktör', 'Otomotiv'),
('TUKAS.IS', 'Tukaş Gıda', 'Gıda & İçecek'),
('TUPRS.IS', 'Tüpraş', 'Enerji'),
('TURSG.IS', 'Türkiye Sigorta', 'Sigorta'),
('ULKER.IS', 'Ülker Bisküvi', 'Gıda & İçecek'),
('VAKBN.IS', 'Türkiye Vakıflar Bankası', 'Bankacılık'),
('VERUS.IS', 'Verusa Holding', 'Holding'),
('VESTL.IS', 'Vestel Elektronik', 'Dayanıklı Tüketim'),
('YATAS.IS', 'Yataş Yatak ve Yorgan', 'Dayanıklı Tüketim'),
('YKBNK.IS', 'Yapı ve Kredi Bankası', 'Bankacılık'),
('YUNSA.IS', 'Yünsa Yünlü Sanayi', 'Tekstil'),
('ZOREN.IS', 'Zorlu Enerji', 'Enerji'),
('AGHOL.IS', 'AG Anadolu Grubu Holding', 'Holding'),
('AKFYE.IS', 'Akfen Yenilenebilir Enerji', 'Enerji'),
('CANTE.IS', 'Çan2 Termik Enerji', 'Enerji'),
('NUGYO.IS', 'Nurol GYO', 'Gayrimenkul'),
('MAVI.IS', 'Mavi Giyim', 'Tekstil'),
('SARKY.IS', 'Sarkuysan Elektrolitik Bakır', 'Metal & Çelik'),
('SMRTG.IS', 'Smart Güneş Enerjisi', 'Enerji');

-- ============================================================
-- Toplam kayıt sayısını kontrol et
-- ============================================================
SELECT 'company_analysis_core (S&P)' AS tablo, COUNT(*) AS kayit_sayisi FROM company_analysis_core
UNION ALL
SELECT 'company_analysis_tr_core (BIST)' AS tablo, COUNT(*) AS kayit_sayisi FROM company_analysis_tr_core;
